# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: CI

on:
  push:
    paths:
      - 'abp/**/*'
      - 'base/**/*'
      - 'hardened/**/*'
      - 'wildcards-no-star/**/*'
      - 'wildcards-star/**/*'
      - 'scripts/**/*'
      - '.forgejo/workflows/**/*'

env:
  BADBLOCK_CI: 1
  BADBLOCK_CHECKOUT_ACTION_COMMIT: "f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a" # v7.0.1
  BADBLOCK_FEDORA_VERSION: "44"
  BADBLOCK_PROD_BRANCH: "pages"

jobs:
  lint:
    name: Lint
    runs-on: codeberg-medium
    container:
      image: fedora:${{ env.BADBLOCK_FEDORA_VERSION }}
    steps:
      - name: Get dependencies
        run: |
          set -euo pipefail
          /bin/sudo /bin/dnf update -y --refresh
          /bin/sudo /bin/dnf install -y node

      - name: Checkout repo
        uses: actions/checkout@${{ env.BADBLOCK_CHECKOUT_ACTION_COMMIT }}

      - name: Lint
        run: |
          set -euo pipefail
          /bin/sudo /bin/dnf update -y --refresh
          /bin/sudo /bin/dnf install -y bash curl shasum tar
          /bin/bash scripts/get_sources.sh shellcheck
          /bin/bash scripts/get_sources.sh shfmt
          /bin/bash scripts/lint.sh

  push-lists:
    name: Push lists
    if: forgejo.ref_name == env.BADBLOCK_PROD_BRANCH && forgejo.repository == 'celenity/BadBlock'
    needs: [lint]
    runs-on: codeberg-medium
    container:
      image: fedora:${{ env.BADBLOCK_FEDORA_VERSION }}
    steps:
      - name: Get dependencies
        run: |
          set -euo pipefail
          /bin/sudo /bin/dnf update -y --refresh
          /bin/sudo /bin/dnf install -y node

      - name: Checkout repo
        uses: actions/checkout@${{ env.BADBLOCK_CHECKOUT_ACTION_COMMIT }}

      - name: Push lists
        env:
          BADBLOCK_S3_ACCESS_KEY: ${{ secrets.BADBLOCK_S3_ACCESS_KEY }}
          BADBLOCK_S3_BUCKET_NAME: ${{ secrets.BADBLOCK_S3_BUCKET_NAME }}
          BADBLOCK_S3_ENDPOINT: ${{ secrets.BADBLOCK_S3_ENDPOINT }}
          BADBLOCK_S3_SECRET_KEY: ${{ secrets.BADBLOCK_S3_SECRET_KEY }}
        run: |
          set -euo pipefail
          /bin/bash scripts/ci-push-lists.sh
