# BadBlock common environment variables

## CAUTION: Do NOT source this directly!
## Source 'env.sh' instead.

## Additionally, if you need to override any variables here, export them to your shell manually or use `env_override.sh`.
## Do NOT edit this file directly.

# BadBlock

# Scripts directory
readonly BADBLOCK_SCRIPTS="${BADBLOCK_ROOT}/scripts"
export BADBLOCK_SCRIPTS

# Set our platform, OS, and architecture
readonly BADBLOCK_ENV_HELPERS="${BADBLOCK_SCRIPTS}/env_helpers.sh"
export BADBLOCK_ENV_HELPERS
source "${BADBLOCK_ENV_HELPERS}"

# Do not use the system PATH
unset PATH

# If variables are defined with a custom `env_override.sh` file (located at the root project directory), let's use those
## These need to be set first, to ensure that they don't interfere with certain variables
readonly BADBLOCK_ENV_OVERRIDE="${BADBLOCK_ROOT}/env_override.sh"
if [[ -f "${BADBLOCK_ENV_OVERRIDE}" ]]; then
  source "${BADBLOCK_ENV_OVERRIDE}"
fi

## BadBlock utilities
readonly BADBLOCK_UTILS="${BADBLOCK_SCRIPTS}/utilities.sh"
export BADBLOCK_UTILS

# Build directory
readonly BADBLOCK_BUILD_DEFAULT="${BADBLOCK_ROOT}/build"
if [[ -z "${BADBLOCK_BUILD+x}" ]]; then
  BADBLOCK_BUILD="${BADBLOCK_BUILD_DEFAULT}"
fi
readonly BADBLOCK_BUILD
export BADBLOCK_BUILD

# BadBlock PATH
readonly BADBLOCK_PATH="${BADBLOCK_BUILD}/path"
export BADBLOCK_PATH

# External sources directory
readonly BADBLOCK_EXTERNAL="${BADBLOCK_ROOT}/external"
export BADBLOCK_EXTERNAL

# External downloads/resources directory
readonly BADBLOCK_DOWNLOADS="${BADBLOCK_EXTERNAL}/downloads"
export BADBLOCK_DOWNLOADS

# Version info
readonly BADBLOCK_VERSIONS="${BADBLOCK_SCRIPTS}/versions.sh"
export BADBLOCK_VERSIONS

# Should we create a log file for build.sh? (Default)
readonly BADBLOCK_LOG_BUILD_DEFAULT=1
if [[ -z "${BADBLOCK_LOG_BUILD+x}" ]]; then
  BADBLOCK_LOG_BUILD="${BADBLOCK_LOG_BUILD_DEFAULT}"
fi
readonly BADBLOCK_LOG_BUILD
export BADBLOCK_LOG_BUILD

# Should we create a log file for get_sources.sh? (Default)
readonly BADBLOCK_LOG_SOURCES_DEFAULT=1
if [[ -z "${BADBLOCK_LOG_SOURCES+x}" ]]; then
  BADBLOCK_LOG_SOURCES="${BADBLOCK_LOG_SOURCES_DEFAULT}"
fi
readonly BADBLOCK_LOG_SOURCES
export BADBLOCK_LOG_SOURCES

# Should we create a log file for push_assets.sh? (Default)
readonly BADBLOCK_LOG_PUSH_DEFAULT=1
if [[ -z "${BADBLOCK_LOG_PUSH+x}" ]]; then
  BADBLOCK_LOG_PUSH="${BADBLOCK_LOG_PUSH_DEFAULT}"
fi
readonly BADBLOCK_LOG_PUSH
export BADBLOCK_LOG_PUSH

# Directory where we should store log files (if logging is desired)
readonly BADBLOCK_LOG_DIR_DEFAULT="${BADBLOCK_BUILD}/logs"
if [[ -z "${BADBLOCK_LOG_DIR+x}" ]]; then
  BADBLOCK_LOG_DIR="${BADBLOCK_LOG_DIR_DEFAULT}"
fi
readonly BADBLOCK_LOG_DIR
export BADBLOCK_LOG_DIR

# basename
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_BASENAME_DEFAULT='/usr/bin/basename'
else
  readonly BADBLOCK_BASENAME_DEFAULT='/bin/basename'
fi
if [[ -z "${BADBLOCK_BASENAME+x}" ]]; then
  BADBLOCK_BASENAME="${BADBLOCK_BASENAME_DEFAULT}"
fi
readonly BADBLOCK_BASENAME
export BADBLOCK_BASENAME

# cat
readonly BADBLOCK_CAT_DEFAULT='/bin/cat'
if [[ -z "${BADBLOCK_CAT+x}" ]]; then
  BADBLOCK_CAT="${BADBLOCK_CAT_DEFAULT}"
fi
readonly BADBLOCK_CAT
export BADBLOCK_CAT

# chmod
readonly BADBLOCK_CHMOD_DEFAULT='/bin/chmod'
if [[ -z "${BADBLOCK_CHMOD+x}" ]]; then
  BADBLOCK_CHMOD="${BADBLOCK_CHMOD_DEFAULT}"
fi
readonly BADBLOCK_CHMOD
export BADBLOCK_CHMOD

# cp
readonly BADBLOCK_CP_DEFAULT='/bin/cp'
if [[ -z "${BADBLOCK_CP+x}" ]]; then
  BADBLOCK_CP="${BADBLOCK_CP_DEFAULT}"
fi
readonly BADBLOCK_CP
export BADBLOCK_CP

# curl
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_CURL_DEFAULT='/opt/homebrew/opt/curl/bin/curl'
else
  readonly BADBLOCK_CURL_DEFAULT='/bin/curl'
fi
if [[ -z "${BADBLOCK_CURL+x}" ]]; then
  BADBLOCK_CURL="${BADBLOCK_CURL_DEFAULT}"
fi
readonly BADBLOCK_CURL
export BADBLOCK_CURL

# dirname
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_DIRNAME_DEFAULT='/usr/bin/dirname'
else
  readonly BADBLOCK_DIRNAME_DEFAULT='/bin/dirname'
fi
if [[ -z "${BADBLOCK_DIRNAME+x}" ]]; then
  BADBLOCK_DIRNAME="${BADBLOCK_DIRNAME_DEFAULT}"
fi
readonly BADBLOCK_DIRNAME
export BADBLOCK_DIRNAME

# dot_clean
readonly BADBLOCK_DOT_CLEAN_DEFAULT='/usr/sbin/dot_clean'
if [[ -z "${BADBLOCK_DOT_CLEAN+x}" ]]; then
  BADBLOCK_DOT_CLEAN="${BADBLOCK_DOT_CLEAN_DEFAULT}"
fi
readonly BADBLOCK_DOT_CLEAN
export BADBLOCK_DOT_CLEAN

# find
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_FIND_DEFAULT='/usr/bin/find'
else
  readonly BADBLOCK_FIND_DEFAULT='/bin/find'
fi
if [[ -z "${BADBLOCK_FIND+x}" ]]; then
  BADBLOCK_FIND="${BADBLOCK_FIND_DEFAULT}"
fi
readonly BADBLOCK_FIND
export BADBLOCK_FIND

# git
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_GIT_DEFAULT='/opt/homebrew/bin/git'
else
  readonly BADBLOCK_GIT_DEFAULT='/bin/git'
fi
if [[ -z "${BADBLOCK_GIT+x}" ]]; then
  BADBLOCK_GIT="${BADBLOCK_GIT_DEFAULT}"
fi
readonly BADBLOCK_GIT
export BADBLOCK_GIT

# GNU awk
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_AWK_DEFAULT='/opt/homebrew/bin/gawk'
else
  readonly BADBLOCK_AWK_DEFAULT='/bin/awk'
fi
if [[ -z "${BADBLOCK_AWK+x}" ]]; then
  BADBLOCK_AWK="${BADBLOCK_AWK_DEFAULT}"
fi
readonly BADBLOCK_AWK
export BADBLOCK_AWK

# GNU date
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_DATE_DEFAULT='/opt/homebrew/bin/gdate'
else
  readonly BADBLOCK_DATE_DEFAULT='/bin/date'
fi
if [[ -z "${BADBLOCK_DATE+x}" ]]; then
  BADBLOCK_DATE="${BADBLOCK_DATE_DEFAULT}"
fi
readonly BADBLOCK_DATE
export BADBLOCK_DATE

# GNU sed
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_SED_DEFAULT='/opt/homebrew/bin/gsed'
else
  readonly BADBLOCK_SED_DEFAULT='/bin/sed'
fi
if [[ -z "${BADBLOCK_SED+x}" ]]; then
  BADBLOCK_SED="${BADBLOCK_SED_DEFAULT}"
fi
readonly BADBLOCK_SED
export BADBLOCK_SED

# GNU tar
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_TAR_DEFAULT='/opt/homebrew/bin/gtar'
else
  readonly BADBLOCK_TAR_DEFAULT='/bin/tar'
fi
if [[ -z "${BADBLOCK_TAR+x}" ]]; then
  BADBLOCK_TAR="${BADBLOCK_TAR_DEFAULT}"
fi
readonly BADBLOCK_TAR
export BADBLOCK_TAR

# grep
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_GREP_DEFAULT='/usr/bin/grep'
else
  readonly BADBLOCK_GREP_DEFAULT='/bin/grep'
fi
if [[ -z "${BADBLOCK_GREP+x}" ]]; then
  BADBLOCK_GREP="${BADBLOCK_GREP_DEFAULT}"
fi
readonly BADBLOCK_GREP
export BADBLOCK_GREP

# gzip
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_GZIP_DEFAULT='/usr/bin/gzip'
else
  readonly BADBLOCK_GZIP_DEFAULT='/bin/gzip'
fi
if [[ -z "${BADBLOCK_GZIP+x}" ]]; then
  BADBLOCK_GZIP="${BADBLOCK_GZIP_DEFAULT}"
fi
readonly BADBLOCK_GZIP
export BADBLOCK_GZIP

# ln
readonly BADBLOCK_LN_DEFAULT='/bin/ln'
if [[ -z "${BADBLOCK_LN+x}" ]]; then
  BADBLOCK_LN="${BADBLOCK_LN_DEFAULT}"
fi
readonly BADBLOCK_LN
export BADBLOCK_LN

# ls
readonly BADBLOCK_LS_DEFAULT='/bin/ls'
if [[ -z "${BADBLOCK_LS+x}" ]]; then
  BADBLOCK_LS="${BADBLOCK_LS_DEFAULT}"
fi
readonly BADBLOCK_LS
export BADBLOCK_LS

# md5sum
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_MD5SUM_DEFAULT='/sbin/md5sum'
else
  readonly BADBLOCK_MD5SUM_DEFAULT='/bin/md5sum'
fi
if [[ -z "${BADBLOCK_MD5SUM+x}" ]]; then
  BADBLOCK_MD5SUM="${BADBLOCK_MD5SUM_DEFAULT}"
fi
readonly BADBLOCK_MD5SUM
export BADBLOCK_MD5SUM

# mkdir
readonly BADBLOCK_MKDIR_DEFAULT='/bin/mkdir'
if [[ -z "${BADBLOCK_MKDIR+x}" ]]; then
  BADBLOCK_MKDIR="${BADBLOCK_MKDIR_DEFAULT}"
fi
readonly BADBLOCK_MKDIR
export BADBLOCK_MKDIR

# mv
readonly BADBLOCK_MV_DEFAULT='/bin/mv'
if [[ -z "${BADBLOCK_MV+x}" ]]; then
  BADBLOCK_MV="${BADBLOCK_MV_DEFAULT}"
fi
readonly BADBLOCK_MV
export BADBLOCK_MV

# rm
readonly BADBLOCK_RM_DEFAULT='/bin/rm'
if [[ -z "${BADBLOCK_RM+x}" ]]; then
  BADBLOCK_RM="${BADBLOCK_RM_DEFAULT}"
fi
readonly BADBLOCK_RM
export BADBLOCK_RM

# shasum
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_SHASUM_DEFAULT='/opt/homebrew/bin/shasum'
elif [[ "${BADBLOCK_OS}" == 'secureblue' ]]; then
  readonly BADBLOCK_SHASUM_DEFAULT='/home/linuxbrew/.linuxbrew/bin/shasum'
else
  readonly BADBLOCK_SHASUM_DEFAULT='/bin/shasum'
fi
if [[ -z "${BADBLOCK_SHASUM+x}" ]]; then
  BADBLOCK_SHASUM="${BADBLOCK_SHASUM_DEFAULT}"
fi
readonly BADBLOCK_SHASUM
export BADBLOCK_SHASUM

# sort
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_SORT_DEFAULT='/usr/bin/sort'
else
  readonly BADBLOCK_SORT_DEFAULT='/bin/sort'
fi
if [[ -z "${BADBLOCK_SORT+x}" ]]; then
  BADBLOCK_SORT="${BADBLOCK_SORT_DEFAULT}"
fi
readonly BADBLOCK_SORT
export BADBLOCK_SORT

# tee
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_TEE_DEFAULT='/usr/bin/tee'
else
  readonly BADBLOCK_TEE_DEFAULT='/bin/tee'
fi
if [[ -z "${BADBLOCK_TEE+x}" ]]; then
  BADBLOCK_TEE="${BADBLOCK_TEE_DEFAULT}"
fi
readonly BADBLOCK_TEE
export BADBLOCK_TEE

# touch
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_TOUCH_DEFAULT='/usr/bin/touch'
else
  readonly BADBLOCK_TOUCH_DEFAULT='/bin/touch'
fi
if [[ -z "${BADBLOCK_TOUCH+x}" ]]; then
  BADBLOCK_TOUCH="${BADBLOCK_TOUCH_DEFAULT}"
fi
readonly BADBLOCK_TOUCH
export BADBLOCK_TOUCH

# uname
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_UNAME_DEFAULT='/usr/bin/uname'
else
  readonly BADBLOCK_UNAME_DEFAULT='/bin/uname'
fi
if [[ -z "${BADBLOCK_UNAME+x}" ]]; then
  BADBLOCK_UNAME="${BADBLOCK_UNAME_DEFAULT}"
fi
readonly BADBLOCK_UNAME
export BADBLOCK_UNAME

# uniq
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_UNIQ_DEFAULT='/usr/bin/uniq'
else
  readonly BADBLOCK_UNIQ_DEFAULT='/bin/uniq'
fi
if [[ -z "${BADBLOCK_UNIQ+x}" ]]; then
  BADBLOCK_UNIQ="${BADBLOCK_UNIQ_DEFAULT}"
fi
readonly BADBLOCK_UNIQ
export BADBLOCK_UNIQ

# unzip
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_UNZIP_DEFAULT='/usr/bin/unzip'
else
  readonly BADBLOCK_UNZIP_DEFAULT='/bin/unzip'
fi
if [[ -z "${BADBLOCK_UNZIP+x}" ]]; then
  BADBLOCK_UNZIP="${BADBLOCK_UNZIP_DEFAULT}"
fi
readonly BADBLOCK_UNZIP
export BADBLOCK_UNZIP

# xargs
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
  readonly BADBLOCK_XARGS_DEFAULT='/usr/bin/xargs'
else
  readonly BADBLOCK_XARGS_DEFAULT='/bin/xargs'
fi
if [[ -z "${BADBLOCK_XARGS+x}" ]]; then
  BADBLOCK_XARGS="${BADBLOCK_XARGS_DEFAULT}"
fi
readonly BADBLOCK_XARGS
export BADBLOCK_XARGS

# Python
readonly BADBLOCK_PYTHON_DIR_DEFAULT="${BADBLOCK_EXTERNAL}/python"
if [[ -z "${BADBLOCK_PYTHON_DIR+x}" ]]; then
  BADBLOCK_PYTHON_DIR="${BADBLOCK_PYTHON_DIR_DEFAULT}"
fi
readonly BADBLOCK_PYTHON_DIR
export BADBLOCK_PYTHON_DIR

# Python (UV) environment
readonly BADBLOCK_PYENV_DIR_DEFAULT="${BADBLOCK_BUILD}/pyenv"
if [[ -z "${BADBLOCK_PYENV_DIR+x}" ]]; then
  BADBLOCK_PYENV_DIR="${BADBLOCK_PYENV_DIR_DEFAULT}"
fi
readonly BADBLOCK_PYENV_DIR
readonly BADBLOCK_PYENV="${BADBLOCK_PYENV_DIR}/bin/activate"
readonly BADBLOCK_PYTHON="${BADBLOCK_PYENV_DIR}/bin/python"
export BADBLOCK_PYENV
export BADBLOCK_PYENV_DIR
export BADBLOCK_PYTHON

# s3cmd
readonly BADBLOCK_S3CMD_DIR_DEFAULT="${BADBLOCK_EXTERNAL}/s3cmd"
if [[ -z "${BADBLOCK_S3CMD_DIR+x}" ]]; then
  BADBLOCK_S3CMD_DIR="${BADBLOCK_S3CMD_DIR_DEFAULT}"
fi
readonly BADBLOCK_S3CMD_DIR
readonly BADBLOCK_S3CMD="${BADBLOCK_PYENV_DIR}/bin/s3cmd"
export BADBLOCK_S3CMD
export BADBLOCK_S3CMD_DIR

# UV
readonly BADBLOCK_UV_DIR_DEFAULT="${BADBLOCK_EXTERNAL}/uv"
if [[ -z "${BADBLOCK_UV_DIR+x}" ]]; then
  BADBLOCK_UV_DIR="${BADBLOCK_UV_DIR_DEFAULT}"
fi
readonly BADBLOCK_UV_DIR
readonly BADBLOCK_UV="${BADBLOCK_UV_DIR}/uv"
export BADBLOCK_UV
export BADBLOCK_UV_DIR

# UV (local directory)
readonly BADBLOCK_UV_LOCAL_DEFAULT="${BADBLOCK_BUILD}/uv"
if [[ -z "${BADBLOCK_UV_LOCAL+x}" ]]; then
  BADBLOCK_UV_LOCAL="${BADBLOCK_UV_LOCAL_DEFAULT}"
fi
readonly BADBLOCK_UV_LOCAL
export BADBLOCK_UV_LOCAL

# UV cache
readonly BADBLOCK_UV_CACHE_DEFAULT="${BADBLOCK_UV_LOCAL}/cache"
if [[ -z "${BADBLOCK_UV_CACHE+x}" ]]; then
  BADBLOCK_UV_CACHE="${BADBLOCK_UV_CACHE_DEFAULT}"
fi
readonly BADBLOCK_UV_CACHE
export BADBLOCK_UV_CACHE

# UV Python directory
readonly BADBLOCK_UV_PYTHON_DEFAULT="${BADBLOCK_UV_LOCAL}/python"
if [[ -z "${BADBLOCK_UV_PYTHON+x}" ]]; then
  BADBLOCK_UV_PYTHON="${BADBLOCK_UV_PYTHON_DEFAULT}"
fi
readonly BADBLOCK_UV_PYTHON
export BADBLOCK_UV_PYTHON

# UV tools
readonly BADBLOCK_UV_TOOLS_DEFAULT="${BADBLOCK_UV_LOCAL}/tools"
if [[ -z "${BADBLOCK_UV_TOOLS+x}" ]]; then
  BADBLOCK_UV_TOOLS="${BADBLOCK_UV_TOOLS_DEFAULT}"
fi
readonly BADBLOCK_UV_TOOLS
export BADBLOCK_UV_TOOLS

# Cipher suites
## (These enforce strong cipher suites - see ex. https://browserleaks.com/tls)

## For TLS 1.3 connections
### https://curl.se/docs/manpage.html#--tls13-ciphers
readonly BADBLOCK_TLS13_CIPHERS_DEFAULT='TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384'
if [[ -z "${BADBLOCK_TLS13_CIPHERS+x}" ]]; then
  BADBLOCK_TLS13_CIPHERS="${BADBLOCK_TLS13_CIPHERS_DEFAULT}"
fi
readonly BADBLOCK_TLS13_CIPHERS
export BADBLOCK_TLS13_CIPHERS

## For non-TLS 1.3 connections
### https://curl.se/docs/manpage.html#--ciphers
readonly BADBLOCK_NONTLS13_CIPHERS_DEFAULT='ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384'
if [[ -z "${BADBLOCK_NONTLS13_CIPHERS+x}" ]]; then
  BADBLOCK_NONTLS13_CIPHERS="${BADBLOCK_NONTLS13_CIPHERS_DEFAULT}"
fi
readonly BADBLOCK_NONTLS13_CIPHERS
export BADBLOCK_NONTLS13_CIPHERS

# This includes all ciphers (combining BADBLOCK_TLS13_CIPHERS + BADBLOCK_NONTLS13_CIPHERS)
## Useful because many programs do not require specifying a separate set of ciphers for TLS 1.3 like curl does
readonly BADBLOCK_CIPHERS="${BADBLOCK_TLS13_CIPHERS}:${BADBLOCK_NONTLS13_CIPHERS}"
export BADBLOCK_CIPHERS

# If curl flags are added, this determines whether they should be appended to our default flags (default),
## or if they should override them entirely
readonly BADBLOCK_CURL_FLAGS_OVERRIDE_DEFAULT=0
if [[ -z "${BADBLOCK_CURL_FLAGS_OVERRIDE+x}" ]]; then
  BADBLOCK_CURL_FLAGS_OVERRIDE="${BADBLOCK_CURL_FLAGS_OVERRIDE_DEFAULT}"
fi
readonly BADBLOCK_CURL_FLAGS_OVERRIDE
export BADBLOCK_CURL_FLAGS_OVERRIDE

# curl flags
readonly BADBLOCK_CURL_FLAGS_DEFAULT="--disable --no-netrc --ciphers ${BADBLOCK_NONTLS13_CIPHERS} --clobber --create-dirs --delegation none --disallow-username-in-url --doh-cert-status --fail --fail-early --junk-session-cookies --no-basic --no-ca-native --no-digest --no-doh-insecure --no-http0.9 --no-insecure --no-negotiate --no-ntlm --no-proxy-basic --no-proxy-ca-native --no-proxy-digest --no-proxy-insecure --no-proxy-ssl-auto-client-cert --no-sessionid --no-ssl-auto-client-cert --no-ssl-no-revoke --no-ssl-revoke-best-effort --no-xattr --parallel --post301 --post302 --post303 --progress-meter --proto -all,https --proto-default https --proto-redir -all,https --proxy-ciphers ${BADBLOCK_NONTLS13_CIPHERS} --proxy-tls13-ciphers ${BADBLOCK_TLS13_CIPHERS} --referer '' --remove-on-error --retry 5 --retry-all-errors --retry-connrefused --show-error --tls13-ciphers ${BADBLOCK_TLS13_CIPHERS} --tlsv1.2 --trace-time --user-agent '' --verbose"
if [[ -z "${BADBLOCK_CURL_FLAGS+x}" ]]; then
  BADBLOCK_CURL_FLAGS="${BADBLOCK_CURL_FLAGS_DEFAULT}"
elif [[ "${BADBLOCK_CURL_FLAGS_OVERRIDE}" == 1 ]]; then
  BADBLOCK_CURL_FLAGS="${BADBLOCK_CURL_FLAGS}"
else
  BADBLOCK_CURL_FLAGS="${BADBLOCK_CURL_FLAGS_DEFAULT} ${BADBLOCK_CURL_FLAGS}"
fi
readonly BADBLOCK_CURL_FLAGS
export BADBLOCK_CURL_FLAGS

# If s3cmd flags are added, this determines whether they should be appended to our default flags (default),
## or if they should override them entirely
readonly BADBLOCK_S3CMD_FLAGS_OVERRIDE_DEFAULT=0
if [[ -z "${BADBLOCK_S3CMD_FLAGS_OVERRIDE+x}" ]]; then
  BADBLOCK_S3CMD_FLAGS_OVERRIDE="${BADBLOCK_S3CMD_FLAGS_OVERRIDE_DEFAULT}"
fi
readonly BADBLOCK_S3CMD_FLAGS_OVERRIDE
export BADBLOCK_S3CMD_FLAGS_OVERRIDE

# s3cmd flags
readonly BADBLOCK_S3CMD_FLAGS_DEFAULT='--check-certificate --check-hostname --check-md5 --no-guess-mime-type --no-mime-magic --progress --ssl'
if [[ -z "${BADBLOCK_S3CMD_FLAGS+x}" ]]; then
  BADBLOCK_S3CMD_FLAGS="${BADBLOCK_S3CMD_FLAGS_DEFAULT}"
elif [[ "${BADBLOCK_S3CMD_FLAGS_OVERRIDE}" == 1 ]]; then
  BADBLOCK_S3CMD_FLAGS="${BADBLOCK_S3CMD_FLAGS}"
else
  BADBLOCK_S3CMD_FLAGS="${BADBLOCK_S3CMD_FLAGS_DEFAULT} ${BADBLOCK_S3CMD_FLAGS}"
fi
readonly BADBLOCK_S3CMD_FLAGS
export BADBLOCK_S3CMD_FLAGS

# S3

# S3 access key
readonly BADBLOCK_S3_ACCESS_KEY_FILE_DEFAULT='/opt/celenity/celenity-badblock-s3-access-key.txt'
if [[ -z "${BADBLOCK_S3_ACCESS_KEY_FILE+x}" ]]; then
  BADBLOCK_S3_ACCESS_KEY_FILE="${BADBLOCK_S3_ACCESS_KEY_FILE_DEFAULT}"
fi
readonly BADBLOCK_S3_ACCESS_KEY_FILE
export BADBLOCK_S3_ACCESS_KEY_FILE

# S3 bucket name
readonly BADBLOCK_S3_BUCKET_NAME_FILE_DEFAULT='/opt/celenity/celenity-badblock-s3-bucket-name.txt'
if [[ -z "${BADBLOCK_S3_BUCKET_NAME_FILE+x}" ]]; then
  BADBLOCK_S3_BUCKET_NAME_FILE="${BADBLOCK_S3_BUCKET_NAME_FILE_DEFAULT}"
fi
readonly BADBLOCK_S3_BUCKET_NAME_FILE
export BADBLOCK_S3_BUCKET_NAME_FILE

# S3 endpoint
readonly BADBLOCK_S3_ENDPOINT_FILE_DEFAULT='/opt/celenity/celenity-badblock-s3-endpoint.txt'
if [[ -z "${BADBLOCK_S3_ENDPOINT_FILE+x}" ]]; then
  BADBLOCK_S3_ENDPOINT_FILE="${BADBLOCK_S3_ENDPOINT_FILE_DEFAULT}"
fi
readonly BADBLOCK_S3_ENDPOINT_FILE
export BADBLOCK_S3_ENDPOINT_FILE

# S3 secret key
readonly BADBLOCK_S3_SECRET_KEY_FILE_DEFAULT='/opt/celenity/celenity-badblock-s3-secret-key.txt'
if [[ -z "${BADBLOCK_S3_SECRET_KEY_FILE+x}" ]]; then
  BADBLOCK_S3_SECRET_KEY_FILE="${BADBLOCK_S3_SECRET_KEY_FILE_DEFAULT}"
fi
readonly BADBLOCK_S3_SECRET_KEY_FILE
export BADBLOCK_S3_SECRET_KEY_FILE

# Set our external environment variables
readonly BADBLOCK_ENV_EXTERNAL="${BADBLOCK_SCRIPTS}/env_external.sh"
source "${BADBLOCK_ENV_EXTERNAL}"

# We've now set our environment variables...
readonly BADBLOCK_SET_ENVS=1
export BADBLOCK_SET_ENVS
