# BadBlock common environment variables

## CAUTION: Do NOT source this directly!
## Source 'env.sh' instead.

## Additionally, if you need to override any variables here, export them to your shell manually or use `env_override.sh`.
## Do NOT edit this file directly.

# If variables are defined with a custom `env_override.sh` file (located at the root project directory), let's use those
## These need to be set first, to ensure that they don't interfere with certain variables
readonly BADBLOCK_ENV_OVERRIDE="${BADBLOCK_ROOT}/env_override.sh"
if [[ -f "${BADBLOCK_ENV_OVERRIDE}" ]]; then
    source "${BADBLOCK_ENV_OVERRIDE}"
fi

# BadBlock

# Scripts directory
readonly BADBLOCK_SCRIPTS="${BADBLOCK_ROOT}/scripts"
export BADBLOCK_SCRIPTS

## BadBlock utilities
readonly BADBLOCK_UTILS="${BADBLOCK_SCRIPTS}/utilities.sh"
export BADBLOCK_UTILS

# Set our platform and OS
readonly BADBLOCK_ENV_HELPERS="${BADBLOCK_SCRIPTS}/env_helpers.sh"
export BADBLOCK_ENV_HELPERS
source "${BADBLOCK_ENV_HELPERS}"

# Build directory
readonly BADBLOCK_BUILD_DEFAULT="${BADBLOCK_ROOT}/build"
if [[ -z "${BADBLOCK_BUILD+x}" ]]; then
    BADBLOCK_BUILD="${BADBLOCK_BUILD_DEFAULT}"
fi
readonly BADBLOCK_BUILD
export BADBLOCK_BUILD

# Should we create a log file for build.sh? (Default)
readonly BADBLOCK_LOG_BUILD_DEFAULT=1
if [[ -z "${BADBLOCK_LOG_BUILD+x}" ]]; then
    BADBLOCK_LOG_BUILD="${BADBLOCK_LOG_BUILD_DEFAULT}"
fi
readonly BADBLOCK_LOG_BUILD
export BADBLOCK_LOG_BUILD

# Directory where we should store log files (if logging is desired)
readonly BADBLOCK_LOG_DIR_DEFAULT="${BADBLOCK_BUILD}/logs"
if [[ -z "${BADBLOCK_LOG_DIR+x}" ]]; then
    BADBLOCK_LOG_DIR="${BADBLOCK_LOG_DIR_DEFAULT}"
fi
readonly BADBLOCK_LOG_DIR
export BADBLOCK_LOG_DIR

# GNU awk
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
    readonly BADBLOCK_AWK_DEFAULT='gawk'
else
    readonly BADBLOCK_AWK_DEFAULT='awk'
fi
if [[ -z "${BADBLOCK_AWK+x}" ]]; then
    BADBLOCK_AWK="${BADBLOCK_AWK_DEFAULT}"
fi
readonly BADBLOCK_AWK
export BADBLOCK_AWK

# GNU date
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
    readonly BADBLOCK_DATE_DEFAULT='gdate'
else
    readonly BADBLOCK_DATE_DEFAULT='date'
fi
if [[ -z "${BADBLOCK_DATE+x}" ]]; then
    BADBLOCK_DATE="${BADBLOCK_DATE_DEFAULT}"
fi
readonly BADBLOCK_DATE
export BADBLOCK_DATE

# GNU sed
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
    readonly BADBLOCK_SED_DEFAULT='gsed'
else
    readonly BADBLOCK_SED_DEFAULT='sed'
fi
if [[ -z "${BADBLOCK_SED+x}" ]]; then
    BADBLOCK_SED="${BADBLOCK_SED_DEFAULT}"
fi
readonly BADBLOCK_SED
export BADBLOCK_SED

# GNU tar
if [[ "${BADBLOCK_OS}" == 'osx' ]]; then
    readonly BADBLOCK_TAR_DEFAULT='gtar'
else
    readonly BADBLOCK_TAR_DEFAULT='tar'
fi
if [[ -z "${BADBLOCK_TAR+x}" ]]; then
    BADBLOCK_TAR="${BADBLOCK_TAR_DEFAULT}"
fi
readonly BADBLOCK_TAR
export BADBLOCK_TAR

# We've now set our environment variables...
readonly BADBLOCK_SET_ENVS=1
export BADBLOCK_SET_ENVS
